name: "🚀 release"

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: yarn
      - run: yarn build
      - run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: GITHUB_TOKEN=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 NPM_TOKEN=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 yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

